### ISSUE TITLE
Is there an example for the API to add/delete tags?

### ISSUE THREAD

**Issue by HanYangZhao** [iomz/golemu#33]
I'm trying to figure out what do put in the json parameters, but I'm unsure as to put in "length" and "readData" from swagger.yaml

**Comment by iomz** [comment]
The swagger description is totally outdated as I shifted from the Web API to the `simulator` mode as I needed to deal with thousands of tags – with the Web API the latency/overhead was too high. The `length` was the total length for non-GS1 EPC and `readData` was the C1G2ReadOpSpecResult's `ReadData` to simulate the read of the user memory.

The web API is, however, [still available](https://github.com/iomz/golemu/blob/8dd0e78db77b89d979ade4783c18bc44c3c58710/main.go#L96) in `server` mode simply taking [`TagRecord`](https://github.com/iomz/go-llrp/blob/6041d5c17a640f170da17abbffed4414f0f5acfb/tag_record.go) from `go-llrp`.

E.g., 
```
% cat tags.json
[
    {
        "PCbits": "3000",
        "EPC": "307227627f2ea48000001c6a"
    }
]
% curl -X POST http://localhost:8080/api/v1/tags -d @tags.json
```

**Comment by HanYangZhao** [comment]
I tried it and it worked! However, golemu doesn't seem to respond to any other curl request after the initial one. All requests seems to hang forever

**Comment by iomz** [comment]
It seems golemu now has a bug with the deprecated BindWith(). The HTTP connection handling should be fixed.

**Comment by HanYangZhao** [comment]
I updated  BindWith() to MustBindWith(), problem still seems to persists
